
project_id = "igjnhwvtasegwyiwcdkr"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 14

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[storage]
file_size_limit = "50MiB"

[functions.create-hookdeck-webhook]
verify_jwt = true

[functions.delete-hookdeck-source]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.handle-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.test-actblue-webhook]
verify_jwt = true

[functions.update-hookdeck-source]
verify_jwt = true

[functions.upload-actblue-logo]
verify_jwt = true
