// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igjnhwvtasegwyiwcdkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnam5od3Z0YXNlZ3d5aXdjZGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzAzNDUsImV4cCI6MjA1ODcwNjM0NX0.secGhh6THLQ8ODvHeG9TlbZ-_KHIKjI_gCRsMZN4Kvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);